### ISSUE TITLE
Security consideration for cases that should use a cut

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/cddl#19]
If spec authors rely on CDDL checking to verify that structures have an expected shape, the lack of general cuts could cause malicious data to get to places that don't expect it. For example, if someone were to define an extensible array:

```
arr = [*elem]
elem /= { type: "foo", val: tstr .size 16 }
elem /= { type: "bar", val: uint }
elem /= { type: tstr, val: any }  ; For future extensions.
```

then the array `[{type: "foo", val: "0123456789ABCDEFbuffer overflow here"}]` is a valid instance of `arr`. We should warn specification authors and implementers to be careful to avoid that.

**Comment by cabo** [comment]
Right.  The same is true about the example with ants, cats, and elks that I'm using on my slides.
We are limiting the use of cuts to the key position of maps right now because we want to be careful with that new feature, but we can't ship CDDL 1.0 without defining what the ":" shortcut means (which probably also will be the most widely used form of cuts).

More generally, I think we should also advise against making the security of a system depend on the correctness of a CDDL validator without any further defenses in place.

**Comment by cabo** [comment]
(1) I think we should indeed have cuts in CDDL 1.0, for the cases where people had already identified they were expecting this semantics.

(2) I have added some text to the security considerations about this.
